#!/bin/bash
#SBATCH --job-name="IQarr_gtree"
#SBATCH --time=48:00:00  # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=1   # processor core(s) per node
#SBATCH -c 1
#SBATCH --mem-per-cpu=6G
#SBATCH --mail-user="biancani@uri.edu" #CHANGE THIS to your user email address
#SBATCH --mail-type=ALL
#SBATCH --array=[1-260]%40

## UPDATE PATHS as needed...
# path to TreeshrewProject Directory:
PROJECT=/scratch/workspace/biancani_uri_edu-treeshrew/TreeshrewProject
# path to iqtree array work folder:
array_work_folder=$PROJECT/output/iqtree_assessment
# path to aligned, filtered loci:
aligned_loci_path=$PROJECT/output/FilteredByTaxa
# path to IQtree scripts:
scripts_dir=$PROJECT/02_iqtree
# path to IQtree executable:
iqtree_exe="/data/schwartzlab/alex/andromeda_tools/iqtree-2.1.2-Linux/bin/iqtree2"
# path to constraint tree:
CONSTRAINT=$PROJECT/SISRS_Run/RAxML_bestTree.alignment_pi_m25_nogap

module purge
## Andromeda (URI's cluster) specific:
module load R/4.0.3-foss-2020b

date
cd $array_work_folder
mkdir -p GeneTreesConstrained

# extract filelines from array_list.txt (generated by iqtree array prep script)
fileline=$(sed -n ${SLURM_ARRAY_TASK_ID}p $array_work_folder/array_list.txt)

cat $array_work_folder/${fileline} | while read line
do
        echo $line
        prefix=GeneTreesConstrained/inference_${line}
        # Trim constraint tree (remove taxon missing from gene tree):
        Rscript ${scripts_dir}/trimConstraintTree.R ${aligned_loci_path}/${line} ${CONSTRAINT} ${prefix}.constraint.tre
        ${iqtree_exe} -nt 1 -s ${aligned_loci_path}/${line} -pre ${prefix} -alrt 1000 -m GTR+G -g ${prefix}.constraint.tre
        mkdir -p GeneTreesConstrained/iqtree_files/
        # Move iqtree output files to folder:
        mv ${prefix}.iqtree GeneTreesConstrained/iqtree_files/
        mkdir -p GeneTreesConstrained/TrimmedConstraintTrees
        # Move Trimmed Constraint trees to folder:
        mv ${prefix}.constraint.tre GeneTreesConstrained/TrimmedConstraintTrees/
        mkdir -p GeneTreesConstrained/Individual_Constrained_GeneTrees
        # Move constrained gene trees to folder:
        mv ${prefix}.treefile GeneTreesConstrained/Individual_Constrained_GeneTrees
        rm -f ${prefix}.ckp.gz ${prefix}.log ${prefix}.parstree ${prefix}.bionj ${prefix}.mldist ${prefix}.uniqueseq.phy
done
